# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    CtrlpCount = 1

    (1..CtrlpCount).each do |i|
    config.vm.define "vbx-ctrlp-1" do |ctrlp|
            ctrlp.vm.box = "ubuntu/focal64"
            ctrlp.vm.network :private_network, ip: "10.253.253.1#{i}"
            ctrlp.vm.hostname = "vbx-ctrlp-1"
            ctrlp.vm.cloud_init :user_data, content_type: "text/cloud-config", path: "cloud.cfg"
            ctrlp.vm.provider :virtualbox do |v|
                v.memory = 2048
                v.cpus = 2
            end
        end
    end

    NodeCount = 2

    (1..NodeCount).each do |i|
        config.vm.define "vbx-wrker-#{i}" do |node|
            node.vm.box = "ubuntu/focal64"
            node.vm.network :private_network, ip: "10.253.253.1#{i+CtrlpCount}"
            node.vm.hostname = "vbx-wrker-#{i}"
            node.vm.cloud_init :user_data, content_type: "text/cloud-config", path: "cloud.cfg"
            node.vm.provider :virtualbox do |v|
                v.memory = 1536
                v.cpus = 1
            end
        end
    end

    config.vm.box_check_update = false
    config.vbguest.auto_update = false
    config.vm.boot_timeout = 600
end