# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.define "vbx-ctrlp-1" do |v1|
        v1.vm.box = "ubuntu/focal64"
        v1.vm.network :public_network, beidge: "ens32", type: "dhcp"
        v1.vm.hostname = "vbx-ctrl-1"
        v1.vm.cloud_init :user_data, content_type: "text/cloud-config", path: "cloud.cfg"
        v1.vm.cloud_init :user_data, content_type: "text/x-shellscript", path: "modify-kubelet.sh"
        v1.vm.provider :virtualbox do |v|
            v.memory = 2048
            v.cpus = 2
        end
    end

    NodeCount = 2

    (1..NodeCount).each do |i|
        config.vm.define "vbx-wrker-#{i}" do |v2|
            v2.vm.box = "ubuntu/focal64"
            v2.vm.network :public_network, beidge: "ens32", type: "dhcp"
            v2.vm.hostname = "vbx-wrker-#{i}"
            v2.vm.cloud_init :user_data, content_type: "text/cloud-config", path: "cloud.cfg"
            v2.vm.cloud_init :user_data, content_type: "text/x-shellscript", path: "modify-kubelet.sh"
            v2.vm.provider :virtualbox do |v|
                v.memory = 2048
                v.cpus = 2
            end
        end
    end

    config.vm.box_check_update = false
    config.vbguest.auto_update = false
    config.vm.boot_timeout = 600
  end

