apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: mongodb
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      namespace: mongodb
      labels:
        app: mongo-express
    spec:
      # Ref: https://stackoverflow.com/questions/15443106/how-to-check-if-mongodb-is-up-and-ready-to-accept-connections-from-bash-script#:~:text=log%20%2D%2Dlogappend%20%26%20%23%20Wait%20until,%2Fvar%2Flog%2Fmongodb.
      initContainers:
      - name: check-mongo-ready
        image: busybox:1.35.0
        command:
          - sh
        args:
          - -c
          - "until nc -z mongodb-0.mongodb-headless 27017; do echo waiting for mongodb; sleep 2; done;"
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: root
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb-0.mongodb-headless
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-root-password
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mongodb
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
