apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
  local:
    v4pool:
      aggregation: default
      pool: 10.254.254.240-10.254.254.250
      subnet: 10.254.254.0/24
