apiVersion: kubeadm.k8s.io/v1beta3
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: {{ ctrlpName }}:6443
    token: bs9zlw.eqyk56o1igfk5t8p
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: bs9zlw.eqyk56o1igfk5t8p
kind: JoinConfiguration
nodeRegistration:
  criSocket: /var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: {{ wrkerName }}
  taints: null